-- Customs-AI reliable task flow migration for DM8.
-- Every DDL block checks the DM8 catalog so this script can be executed repeatedly.

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_AI_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_AI_AGENT" (
      "AGENT_CODE" VARCHAR(64) NOT NULL,
      "AGENT_NAME" VARCHAR(120) NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "SORT_ORDER" INT DEFAULT 0,
      "DESCRIPTION" VARCHAR(500),
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_AI_AGENT" PRIMARY KEY ("AGENT_CODE")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_CUSTOMER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_CUSTOMER" (
      "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
      "CUSTOMER_NAME" VARCHAR(160) NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_CUSTOMER" PRIMARY KEY ("CUSTOMER_CODE")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_CUSTOMER_USER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_CUSTOMER_USER" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
      "USER_ID" VARCHAR(64) NOT NULL,
      "USERNAME" VARCHAR(100),
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_CUSTOMER_USER" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_USER_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_USER_AGENT" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
      "USER_ID" VARCHAR(64) NOT NULL,
      "AGENT_CODE" VARCHAR(64) NOT NULL,
      "IS_DEFAULT" INT DEFAULT 0 NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_USER_AGENT" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_API_APP_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_API_APP_AGENT" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "APP_ID" BIGINT NOT NULL,
      "AGENT_CODE" VARCHAR(64) NOT NULL,
      "IS_DEFAULT" INT DEFAULT 0 NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_API_APP_AGENT" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_CUSTOMER_USER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_CUSTOMER_USER" ON "CUSTOM_CUSTOMER_USER" ("USER_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_USER_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_USER_AGENT" ON "CUSTOM_USER_AGENT" ("USER_ID", "AGENT_CODE")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_API_APP_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_API_APP_AGENT" ON "CUSTOM_API_APP_AGENT" ("APP_ID", "AGENT_CODE")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CUSTOM_USER_AGENT_CUSTOMER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX "IDX_CUSTOM_USER_AGENT_CUSTOMER" ON "CUSTOM_USER_AGENT" ("CUSTOMER_CODE", "USER_ID")';
  END IF;
END;
/

MERGE INTO "CUSTOM_CUSTOMER" T
USING (SELECT 'INTERNAL' AS "CUSTOMER_CODE", 'Internal' AS "CUSTOMER_NAME" FROM DUAL) S
ON (T."CUSTOMER_CODE" = S."CUSTOMER_CODE")
WHEN NOT MATCHED THEN INSERT ("CUSTOMER_CODE", "CUSTOMER_NAME", "ENABLED", "CREATED_AT", "UPDATED_AT")
VALUES (S."CUSTOMER_CODE", S."CUSTOMER_NAME", 1, SYSDATE, SYSDATE);

MERGE INTO "CUSTOM_AI_AGENT" T
USING (SELECT 'CUSTOMS' AS "AGENT_CODE", '通用' AS "AGENT_NAME", 10 AS "SORT_ORDER" FROM DUAL) S
ON (T."AGENT_CODE" = S."AGENT_CODE")
WHEN NOT MATCHED THEN INSERT ("AGENT_CODE", "AGENT_NAME", "ENABLED", "SORT_ORDER", "CREATED_AT", "UPDATED_AT")
VALUES (S."AGENT_CODE", S."AGENT_NAME", 1, S."SORT_ORDER", SYSDATE, SYSDATE);

MERGE INTO "CUSTOM_AI_AGENT" T
USING (SELECT 'ILLUMNA-CUSTOMS' AS "AGENT_CODE", '因美纳' AS "AGENT_NAME", 20 AS "SORT_ORDER" FROM DUAL) S
ON (T."AGENT_CODE" = S."AGENT_CODE")
WHEN NOT MATCHED THEN INSERT ("AGENT_CODE", "AGENT_NAME", "ENABLED", "SORT_ORDER", "CREATED_AT", "UPDATED_AT")
VALUES (S."AGENT_CODE", S."AGENT_NAME", 1, S."SORT_ORDER", SYSDATE, SYSDATE);

INSERT INTO "CUSTOM_CUSTOMER_USER" ("CUSTOMER_CODE", "USER_ID", "USERNAME", "ENABLED", "CREATED_AT", "UPDATED_AT")
SELECT 'INTERNAL', U."ID", U."USERNAME", 1, SYSDATE, SYSDATE
FROM "SYS_USER" U
WHERE U."USERNAME" = 'admin'
  AND NOT EXISTS (SELECT 1 FROM "CUSTOM_CUSTOMER_USER" CU WHERE CU."USER_ID" = U."ID");

INSERT INTO "CUSTOM_API_APP_AGENT" ("APP_ID", "AGENT_CODE", "IS_DEFAULT", "ENABLED", "CREATED_AT", "UPDATED_AT")
SELECT A."ID", A."COMPANY_CODE", 1, 1, SYSDATE, SYSDATE
FROM "CUSTOM_API_APP" A
WHERE A."COMPANY_CODE" IS NOT NULL
  AND EXISTS (SELECT 1 FROM "CUSTOM_AI_AGENT" G WHERE G."AGENT_CODE" = A."COMPANY_CODE")
  AND NOT EXISTS (
    SELECT 1 FROM "CUSTOM_API_APP_AGENT" AG
    WHERE AG."APP_ID" = A."ID" AND AG."AGENT_CODE" = A."COMPANY_CODE"
  );

COMMIT;
