-- Customs-AI Java facade API tables for DM8.
-- app_secret_hash must be SHA-256 hex of the customer app secret.

CREATE TABLE "CUSTOM_API_APP" (
    "ID" BIGINT IDENTITY(1,1) NOT NULL,
    "APP_KEY" VARCHAR(100) NOT NULL,
    "APP_SECRET_HASH" VARCHAR(128) NOT NULL,
    "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
    "COMPANY_CODE" VARCHAR(64),
    "ENABLED" INT DEFAULT 1,
    "RATE_LIMIT" INT,
    "ACCESS_TOKEN_HASH" VARCHAR(128),
    "TOKEN_EXPIRE_AT" TIMESTAMP,
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP,
    CONSTRAINT "PK_CUSTOM_API_APP" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX "UK_CUSTOM_API_APP_KEY" ON "CUSTOM_API_APP" ("APP_KEY");
CREATE INDEX "IDX_CUSTOM_API_APP_TOKEN" ON "CUSTOM_API_APP" ("ACCESS_TOKEN_HASH");

CREATE TABLE "CUSTOM_API_FILE" (
    "ID" BIGINT IDENTITY(1,1) NOT NULL,
    "FILE_ID" VARCHAR(80) NOT NULL,
    "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
    "CLIENT_FILE_ID" VARCHAR(100),
    "ORIGINAL_FILENAME" VARCHAR(255),
    "CONTENT_TYPE" VARCHAR(120),
    "FILE_SIZE" BIGINT,
    "SHA256" VARCHAR(128),
    "STORAGE_TYPE" VARCHAR(30),
    "BUCKET" VARCHAR(128),
    "OBJECT_KEY" VARCHAR(600),
    "STORAGE_PATH" VARCHAR(600),
    "UPLOAD_TOKEN_HASH" VARCHAR(128),
    "STATUS" VARCHAR(30),
    "CREATED_AT" TIMESTAMP,
    "UPLOADED_AT" TIMESTAMP,
    "EXPIRES_AT" TIMESTAMP,
    CONSTRAINT "PK_CUSTOM_API_FILE" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX "UK_CUSTOM_API_FILE_ID" ON "CUSTOM_API_FILE" ("FILE_ID");
CREATE INDEX "IDX_CUSTOM_API_FILE_CUSTOMER" ON "CUSTOM_API_FILE" ("CUSTOMER_CODE");
CREATE INDEX "IDX_CUSTOM_API_FILE_STATUS" ON "CUSTOM_API_FILE" ("STATUS");

CREATE TABLE "CUSTOM_API_TASK" (
    "ID" BIGINT IDENTITY(1,1) NOT NULL,
    "TASK_ID" VARCHAR(80) NOT NULL,
    "FILE_ID" VARCHAR(80) NOT NULL,
    "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
    "CLIENT_TASK_ID" VARCHAR(100),
    "DOCUMENT_ID" BIGINT,
    "DEC_HEAD_ID" BIGINT,
    "CUSTOMS_AI_JOB_ID" VARCHAR(100),
    "CUSTOMS_AI_RUN_NO" INT,
    "DIRECTION" VARCHAR(20),
    "COMPANY_CODE" VARCHAR(64),
    "CALLBACK_URL" VARCHAR(1000),
    "CALLBACK_SECRET" VARCHAR(255),
    "RESPONSE_MODE" VARCHAR(20),
    "STATUS" VARCHAR(30),
    "STAGE" VARCHAR(60),
    "PROGRESS" INT,
    "METADATA_JSON" CLOB,
    "RESULT_JSON" CLOB,
    "ERROR_CODE" VARCHAR(100),
    "ERROR_MESSAGE" VARCHAR(1000),
    "CALLBACK_STATUS" VARCHAR(30),
    "CALLBACK_ERROR" VARCHAR(1000),
    "CREATED_AT" TIMESTAMP,
    "STARTED_AT" TIMESTAMP,
    "FINISHED_AT" TIMESTAMP,
    CONSTRAINT "PK_CUSTOM_API_TASK" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX "UK_CUSTOM_API_TASK_ID" ON "CUSTOM_API_TASK" ("TASK_ID");
CREATE INDEX "IDX_CUSTOM_API_TASK_CUSTOMER" ON "CUSTOM_API_TASK" ("CUSTOMER_CODE");
CREATE INDEX "IDX_CUSTOM_API_TASK_CLIENT" ON "CUSTOM_API_TASK" ("CLIENT_TASK_ID");
CREATE INDEX "IDX_CUSTOM_API_TASK_STATUS" ON "CUSTOM_API_TASK" ("STATUS");

COMMENT ON TABLE "CUSTOM_API_APP" IS 'Customs-AI external API app credentials';
COMMENT ON TABLE "CUSTOM_API_FILE" IS 'Customs-AI external API uploaded files';
COMMENT ON TABLE "CUSTOM_API_TASK" IS 'Customs-AI external API parse tasks';
