-- Customs-AI reliable task flow migration for DM8.
-- Every DDL block checks the DM8 catalog so this script can be executed repeatedly.

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_AI_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_AI_AGENT" (
      "AGENT_CODE" VARCHAR(64) NOT NULL,
      "AGENT_NAME" VARCHAR(120) NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "SORT_ORDER" INT DEFAULT 0,
      "DESCRIPTION" VARCHAR(500),
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_AI_AGENT" PRIMARY KEY ("AGENT_CODE")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_CUSTOMER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_CUSTOMER" (
      "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
      "CUSTOMER_NAME" VARCHAR(160) NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_CUSTOMER" PRIMARY KEY ("CUSTOMER_CODE")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_CUSTOMER_USER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_CUSTOMER_USER" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
      "USER_ID" VARCHAR(64) NOT NULL,
      "USERNAME" VARCHAR(100),
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_CUSTOMER_USER" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_USER_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_USER_AGENT" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
      "USER_ID" VARCHAR(64) NOT NULL,
      "AGENT_CODE" VARCHAR(64) NOT NULL,
      "IS_DEFAULT" INT DEFAULT 0 NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_USER_AGENT" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_API_APP_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_API_APP_AGENT" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "APP_ID" BIGINT NOT NULL,
      "AGENT_CODE" VARCHAR(64) NOT NULL,
      "IS_DEFAULT" INT DEFAULT 0 NOT NULL,
      "ENABLED" INT DEFAULT 1 NOT NULL,
      "CREATED_AT" TIMESTAMP,
      "UPDATED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_API_APP_AGENT" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_CUSTOMER_USER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_CUSTOMER_USER" ON "CUSTOM_CUSTOMER_USER" ("USER_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_USER_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_USER_AGENT" ON "CUSTOM_USER_AGENT" ("USER_ID", "AGENT_CODE")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_API_APP_AGENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_API_APP_AGENT" ON "CUSTOM_API_APP_AGENT" ("APP_ID", "AGENT_CODE")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CUSTOM_USER_AGENT_CUSTOMER';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX "IDX_CUSTOM_USER_AGENT_CUSTOMER" ON "CUSTOM_USER_AGENT" ("CUSTOMER_CODE", "USER_ID")';
  END IF;
END;
/

MERGE INTO "CUSTOM_CUSTOMER" T
USING (SELECT 'INTERNAL' AS "CUSTOMER_CODE", 'Internal' AS "CUSTOMER_NAME" FROM DUAL) S
ON (T."CUSTOMER_CODE" = S."CUSTOMER_CODE")
WHEN NOT MATCHED THEN INSERT ("CUSTOMER_CODE", "CUSTOMER_NAME", "ENABLED", "CREATED_AT", "UPDATED_AT")
VALUES (S."CUSTOMER_CODE", S."CUSTOMER_NAME", 1, SYSDATE, SYSDATE);

MERGE INTO "CUSTOM_AI_AGENT" T
USING (SELECT 'CUSTOMS' AS "AGENT_CODE", '通用' AS "AGENT_NAME", 10 AS "SORT_ORDER" FROM DUAL) S
ON (T."AGENT_CODE" = S."AGENT_CODE")
WHEN NOT MATCHED THEN INSERT ("AGENT_CODE", "AGENT_NAME", "ENABLED", "SORT_ORDER", "CREATED_AT", "UPDATED_AT")
VALUES (S."AGENT_CODE", S."AGENT_NAME", 1, S."SORT_ORDER", SYSDATE, SYSDATE);

MERGE INTO "CUSTOM_AI_AGENT" T
USING (SELECT 'ILLUMNA-CUSTOMS' AS "AGENT_CODE", '因美纳' AS "AGENT_NAME", 20 AS "SORT_ORDER" FROM DUAL) S
ON (T."AGENT_CODE" = S."AGENT_CODE")
WHEN NOT MATCHED THEN INSERT ("AGENT_CODE", "AGENT_NAME", "ENABLED", "SORT_ORDER", "CREATED_AT", "UPDATED_AT")
VALUES (S."AGENT_CODE", S."AGENT_NAME", 1, S."SORT_ORDER", SYSDATE, SYSDATE);

INSERT INTO "CUSTOM_CUSTOMER_USER" ("CUSTOMER_CODE", "USER_ID", "USERNAME", "ENABLED", "CREATED_AT", "UPDATED_AT")
SELECT 'INTERNAL', U."ID", U."USERNAME", 1, SYSDATE, SYSDATE
FROM "SYS_USER" U
WHERE U."USERNAME" = 'admin'
  AND NOT EXISTS (SELECT 1 FROM "CUSTOM_CUSTOMER_USER" CU WHERE CU."USER_ID" = U."ID");

INSERT INTO "CUSTOM_API_APP_AGENT" ("APP_ID", "AGENT_CODE", "IS_DEFAULT", "ENABLED", "CREATED_AT", "UPDATED_AT")
SELECT A."ID", A."COMPANY_CODE", 1, 1, SYSDATE, SYSDATE
FROM "CUSTOM_API_APP" A
WHERE A."COMPANY_CODE" IS NOT NULL
  AND EXISTS (SELECT 1 FROM "CUSTOM_AI_AGENT" G WHERE G."AGENT_CODE" = A."COMPANY_CODE")
  AND NOT EXISTS (
    SELECT 1 FROM "CUSTOM_API_APP_AGENT" AG
    WHERE AG."APP_ID" = A."ID" AND AG."AGENT_CODE" = A."COMPANY_CODE"
  );

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_FILE' AND COLUMN_NAME = 'APP_ID';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_FILE" ADD "APP_ID" BIGINT';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_FILE' AND COLUMN_NAME = 'IDEMPOTENCY_KEY';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_FILE" ADD "IDEMPOTENCY_KEY" VARCHAR(128)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_FILE' AND COLUMN_NAME = 'REQUEST_HASH';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_FILE" ADD "REQUEST_HASH" VARCHAR(64)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_FILE' AND COLUMN_NAME = 'ACTUAL_FILE_SIZE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_FILE" ADD "ACTUAL_FILE_SIZE" BIGINT';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_FILE' AND COLUMN_NAME = 'ACTUAL_SHA256';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_FILE" ADD "ACTUAL_SHA256" VARCHAR(64)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_FILE' AND COLUMN_NAME = 'VERIFIED_AT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_FILE" ADD "VERIFIED_AT" TIMESTAMP';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_TASK' AND COLUMN_NAME = 'APP_ID';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_TASK" ADD "APP_ID" BIGINT';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_TASK' AND COLUMN_NAME = 'IDEMPOTENCY_KEY';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_TASK" ADD "IDEMPOTENCY_KEY" VARCHAR(128)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_TASK' AND COLUMN_NAME = 'REQUEST_HASH';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_TASK" ADD "REQUEST_HASH" VARCHAR(64)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_TASK' AND COLUMN_NAME = 'LAST_HEARTBEAT_AT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_TASK" ADD "LAST_HEARTBEAT_AT" TIMESTAMP';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_TASK' AND COLUMN_NAME = 'VERSION';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_TASK" ADD "VERSION" INT DEFAULT 0';
  END IF;
END;
/

UPDATE "CUSTOM_API_FILE" F
SET "APP_ID" = (
  SELECT MIN(A."ID") FROM "CUSTOM_API_APP" A WHERE A."CUSTOMER_CODE" = F."CUSTOMER_CODE"
)
WHERE F."APP_ID" IS NULL;

UPDATE "CUSTOM_API_TASK" T
SET "APP_ID" = (
  SELECT MIN(A."ID") FROM "CUSTOM_API_APP" A WHERE A."CUSTOMER_CODE" = T."CUSTOMER_CODE"
)
WHERE T."APP_ID" IS NULL;

UPDATE "CUSTOM_API_TASK" SET "VERSION" = 0 WHERE "VERSION" IS NULL;
UPDATE "CUSTOM_API_TASK" SET "CUSTOMS_AI_RUN_NO" = 1 WHERE "CUSTOMS_AI_RUN_NO" IS NULL;

UPDATE "CUSTOM_API_FILE" F
SET "CLIENT_FILE_ID" = NULL
WHERE F."CLIENT_FILE_ID" IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM "CUSTOM_API_FILE" X
    WHERE X."APP_ID" = F."APP_ID"
      AND X."CLIENT_FILE_ID" = F."CLIENT_FILE_ID"
      AND X."ID" < F."ID"
  );

UPDATE "CUSTOM_API_TASK" T
SET "CLIENT_TASK_ID" = NULL
WHERE T."CLIENT_TASK_ID" IS NOT NULL
  AND EXISTS (
    SELECT 1 FROM "CUSTOM_API_TASK" X
    WHERE X."APP_ID" = T."APP_ID"
      AND X."CLIENT_TASK_ID" = T."CLIENT_TASK_ID"
      AND X."ID" < T."ID"
  );

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_API_FILE_APP_CLIENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_API_FILE_APP_CLIENT" ON "CUSTOM_API_FILE" ("APP_ID", "CLIENT_FILE_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_API_FILE_APP_IDEMP';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_API_FILE_APP_IDEMP" ON "CUSTOM_API_FILE" ("APP_ID", "IDEMPOTENCY_KEY")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_API_FILE_APP_FILE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_API_FILE_APP_FILE" ON "CUSTOM_API_FILE" ("APP_ID", "FILE_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_API_TASK_APP_CLIENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_API_TASK_APP_CLIENT" ON "CUSTOM_API_TASK" ("APP_ID", "CLIENT_TASK_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_API_TASK_APP_IDEMP';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_API_TASK_APP_IDEMP" ON "CUSTOM_API_TASK" ("APP_ID", "IDEMPOTENCY_KEY")';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_MQ_OUTBOX';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_MQ_OUTBOX" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "EVENT_ID" VARCHAR(64) NOT NULL,
      "AGGREGATE_TYPE" VARCHAR(32) NOT NULL,
      "AGGREGATE_ID" VARCHAR(64) NOT NULL,
      "AGGREGATE_VERSION" INT NOT NULL,
      "EVENT_TYPE" VARCHAR(64) NOT NULL,
      "EXCHANGE_NAME" VARCHAR(128) NOT NULL,
      "ROUTING_KEY" VARCHAR(128) NOT NULL,
      "PAYLOAD_JSON" CLOB NOT NULL,
      "STATUS" VARCHAR(16) NOT NULL,
      "ATTEMPT_COUNT" INT DEFAULT 0 NOT NULL,
      "NEXT_ATTEMPT_AT" TIMESTAMP,
      "CLAIMED_AT" TIMESTAMP,
      "SENT_AT" TIMESTAMP,
      "LAST_ERROR" VARCHAR(1000),
      "CREATED_AT" TIMESTAMP NOT NULL,
      "UPDATED_AT" TIMESTAMP NOT NULL,
      CONSTRAINT "PK_CUSTOM_MQ_OUTBOX" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_MQ_OUTBOX_EVENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_MQ_OUTBOX_EVENT" ON "CUSTOM_MQ_OUTBOX" ("EVENT_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_MQ_OUTBOX_AGG';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_MQ_OUTBOX_AGG" ON "CUSTOM_MQ_OUTBOX" ("AGGREGATE_TYPE", "AGGREGATE_ID", "AGGREGATE_VERSION", "EVENT_TYPE")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CUSTOM_MQ_OUTBOX_PENDING';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX "IDX_CUSTOM_MQ_OUTBOX_PENDING" ON "CUSTOM_MQ_OUTBOX" ("STATUS", "NEXT_ATTEMPT_AT")';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_MQ_INBOX';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_MQ_INBOX" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "EVENT_ID" VARCHAR(64) NOT NULL,
      "TASK_ID" VARCHAR(64) NOT NULL,
      "RUN_NO" INT NOT NULL,
      "EVENT_TYPE" VARCHAR(64) NOT NULL,
      "PAYLOAD_HASH" VARCHAR(64) NOT NULL,
      "STATUS" VARCHAR(16) NOT NULL,
      "ERROR_MESSAGE" VARCHAR(1000),
      "RECEIVED_AT" TIMESTAMP NOT NULL,
      "PROCESSED_AT" TIMESTAMP,
      CONSTRAINT "PK_CUSTOM_MQ_INBOX" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_MQ_INBOX_EVENT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_MQ_INBOX_EVENT" ON "CUSTOM_MQ_INBOX" ("EVENT_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CUSTOM_MQ_INBOX_TASK_RUN';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX "IDX_CUSTOM_MQ_INBOX_TASK_RUN" ON "CUSTOM_MQ_INBOX" ("TASK_ID", "RUN_NO")';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = 'CUSTOM_CALLBACK_DELIVERY';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "CUSTOM_CALLBACK_DELIVERY" (
      "ID" BIGINT IDENTITY(1,1) NOT NULL,
      "DELIVERY_ID" VARCHAR(64) NOT NULL,
      "TASK_ID" VARCHAR(64) NOT NULL,
      "RUN_NO" INT NOT NULL,
      "CUSTOMER_CODE" VARCHAR(64) NOT NULL,
      "EVENT_TYPE" VARCHAR(64) NOT NULL,
      "CALLBACK_URL" VARCHAR(2048) NOT NULL,
      "SECRET_CIPHERTEXT" VARCHAR(1000) NOT NULL,
      "SECRET_KEY_VERSION" VARCHAR(32) NOT NULL,
      "PAYLOAD_JSON" CLOB NOT NULL,
      "PAYLOAD_HASH" VARCHAR(64) NOT NULL,
      "STATUS" VARCHAR(16) NOT NULL,
      "ATTEMPT_COUNT" INT DEFAULT 0 NOT NULL,
      "NEXT_ATTEMPT_AT" TIMESTAMP,
      "CLAIMED_AT" TIMESTAMP,
      "LAST_ATTEMPT_AT" TIMESTAMP,
      "DELIVERED_AT" TIMESTAMP,
      "HTTP_STATUS" INT,
      "LAST_ERROR" VARCHAR(1000),
      "CREATED_AT" TIMESTAMP NOT NULL,
      "UPDATED_AT" TIMESTAMP NOT NULL,
      CONSTRAINT "PK_CUSTOM_CALLBACK_DELIVERY" PRIMARY KEY ("ID")
    )';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_CALLBACK_DELIVERY';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_CALLBACK_DELIVERY" ON "CUSTOM_CALLBACK_DELIVERY" ("DELIVERY_ID")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_CUSTOM_CALLBACK_TERMINAL';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_CUSTOM_CALLBACK_TERMINAL" ON "CUSTOM_CALLBACK_DELIVERY" ("TASK_ID", "RUN_NO", "EVENT_TYPE")';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CUSTOM_CALLBACK_PENDING';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX "IDX_CUSTOM_CALLBACK_PENDING" ON "CUSTOM_CALLBACK_DELIVERY" ("STATUS", "NEXT_ATTEMPT_AT")';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_TASK' AND COLUMN_NAME = 'CALLBACK_SECRET_CIPHERTEXT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_TASK" ADD "CALLBACK_SECRET_CIPHERTEXT" VARCHAR(1000)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CUSTOM_API_TASK' AND COLUMN_NAME = 'CALLBACK_SECRET_KEY_VERSION';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "CUSTOM_API_TASK" ADD "CALLBACK_SECRET_KEY_VERSION" VARCHAR(32)';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEC_HEAD' AND COLUMN_NAME = 'SOURCE_TASK_ID';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "DEC_HEAD" ADD "SOURCE_TASK_ID" VARCHAR(64)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEC_HEAD' AND COLUMN_NAME = 'CUSTOMER_CODE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "DEC_HEAD" ADD "CUSTOMER_CODE" VARCHAR(64)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEC_HEAD' AND COLUMN_NAME = 'SOURCE_TYPE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "DEC_HEAD" ADD "SOURCE_TYPE" VARCHAR(32)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DEC_HEAD' AND COLUMN_NAME = 'UPLOADER_USER_ID';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "DEC_HEAD" ADD "UPLOADER_USER_ID" VARCHAR(64)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_INDEXES WHERE INDEX_NAME = 'UK_DEC_HEAD_SOURCE_TASK';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "UK_DEC_HEAD_SOURCE_TASK" ON "DEC_HEAD" ("SOURCE_TASK_ID")';
  END IF;
END;
/

DECLARE
  V_COUNT INT;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DOCUMENTS' AND COLUMN_NAME = 'STAGE';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "DOCUMENTS" ADD "STAGE" VARCHAR(64)';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DOCUMENTS' AND COLUMN_NAME = 'PROGRESS';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "DOCUMENTS" ADD "PROGRESS" INT DEFAULT 0';
  END IF;
  SELECT COUNT(*) INTO V_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'DOCUMENTS' AND COLUMN_NAME = 'LAST_HEARTBEAT_AT';
  IF V_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE "DOCUMENTS" ADD "LAST_HEARTBEAT_AT" TIMESTAMP';
  END IF;
END;
/

COMMIT;
