-- 达梦数据库版本：DEC_HEAD 增加业务事项字段
ALTER TABLE "DEC_HEAD" ADD "BUSINESS_ITEMS" VARCHAR2(5) DEFAULT '00000';

COMMENT ON COLUMN "DEC_HEAD"."BUSINESS_ITEMS" IS '业务事项：说明：1-勾选、0-未勾选 第一位税单无纸化 第二位担保验放 第三位跨境电商海外仓 第四位组合港 第五位自报自享';

UPDATE "DEC_HEAD" SET "BUSINESS_ITEMS" = '00000' WHERE "BUSINESS_ITEMS" IS NULL;
