-- 达梦数据库版本：单一窗口申请单证参数表
-- 用于 DEC_REQUEST_CERT.APP_CERT_CODE 申请单证代码选择，并提供默认正本/副本数量。

CREATE TABLE "PARA_CREDENTIALS" (
    "ID" VARCHAR2(64) NOT NULL,
    "CODE" VARCHAR2(50) NOT NULL,
    "NAME" VARCHAR2(200) NOT NULL,
    "COUNT" INT DEFAULT 0,
    "SUB_COUNT" INT DEFAULT 0,
    CONSTRAINT "PK_PARA_CREDENTIALS" PRIMARY KEY ("ID")
);

CREATE UNIQUE INDEX "UK_PARA_CREDENTIALS_CODE" ON "PARA_CREDENTIALS" ("CODE");

COMMENT ON TABLE "PARA_CREDENTIALS" IS '申请单证参数';
COMMENT ON COLUMN "PARA_CREDENTIALS"."ID" IS '主键';
COMMENT ON COLUMN "PARA_CREDENTIALS"."CODE" IS '申请单证代码';
COMMENT ON COLUMN "PARA_CREDENTIALS"."NAME" IS '申请单证名称';
COMMENT ON COLUMN "PARA_CREDENTIALS"."COUNT" IS '正本数量';
COMMENT ON COLUMN "PARA_CREDENTIALS"."SUB_COUNT" IS '副本数量';

COMMIT;
