-- 单一窗口 CIT 业务测试数据（达梦 DM8 / Oracle 兼容模式）
--
-- 说明：
-- 1. 本脚本覆盖 org.jeecg.modules.custom.cit.entity 包下实体对应的业务表。
-- 2. 所有 ID 均为达梦自增列，本脚本不显式插入 ID，避免触发 IDENTITY_INSERT 报错。
-- 3. 子表通过 DEC_HEAD.PRE_ENTRY_ID = 'TST000001' 回查父表 ID，保证主子表关联正确。
-- 4. 涉及参数字典的字段直接从 PARA_* 表取现有编码；如果 PARA_* 参数表缺失数据，相关 NOT NULL 字段会插入失败，表示基础参数尚未准备好。
-- 5. 脚本可重复执行：执行前会先删除同一批测试数据。

-- ============================================================
-- 清理同一批测试数据
-- ============================================================

DELETE FROM "TRN_CONTA_GOODS_LIST"
 WHERE "TRN_CONTAINER_ID" IN (
       SELECT "ID" FROM "TRN_CONTAINER"
        WHERE "TRN_HEAD_ID" IN (
              SELECT "ID" FROM "TRN_HEAD"
               WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001')
        )
 )
    OR "TRN_LIST_ID" IN (
       SELECT "ID" FROM "TRN_LIST"
        WHERE "TRN_HEAD_ID" IN (
              SELECT "ID" FROM "TRN_HEAD"
               WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001')
        )
 );

DELETE FROM "TRN_CONTAINER"
 WHERE "TRN_HEAD_ID" IN (
       SELECT "ID" FROM "TRN_HEAD"
        WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001')
 );

DELETE FROM "TRN_LIST"
 WHERE "TRN_HEAD_ID" IN (
       SELECT "ID" FROM "TRN_HEAD"
        WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001')
 );

DELETE FROM "TRN_HEAD"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_GOODS_LIMIT_VIN"
 WHERE "DEC_GOODS_LIMIT_ID" IN (
       SELECT "ID" FROM "DEC_GOODS_LIMIT"
        WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001')
 );

DELETE FROM "DEC_CONTROL_MODEL"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "ECO_RELATION"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_SUPPLEMENT"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_GOODS_LIMIT"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_CONTAINER"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_LICENSE_DOCUS"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_REQUEST_CERT"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_OTHER_PACK"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_COP_LIMIT"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_USER"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_MARK_LOB"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_FREE_TXT"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_SIGN"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "EDOC_RELATION"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "SDD_TAX"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_RISK"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_COP_PROMISE"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_ROYALTY_FEE"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_TP_ACCESS"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_LIST"
 WHERE "DEC_HEAD_ID" IN (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001');

DELETE FROM "DEC_HEAD"
 WHERE "PRE_ENTRY_ID" = 'TST000001';

DELETE FROM "CIT_ATTRIBUTES"
 WHERE "VERSION" = 'T1.0';

-- ============================================================
-- 报文属性
-- ============================================================

INSERT INTO "CIT_ATTRIBUTES" ("VERSION")
VALUES ('T1.0');

-- ============================================================
-- 报关单表头：DEC_HEAD
-- 参数来源：
-- CUSTOM_MASTER / IE_PORT / PURP_ORG_CODE -> PARA_CUSTOMS_REL.CUSTOMS_CODE
-- CUT_MODE -> PARA_LEVYTYPE.CUT_MODE
-- TRADE_COUNTRY / TRADE_AREA_CODE -> PARA_COUNTRY.COUNTRY_CO
-- TRADE_MODE -> PARA_TRADE.TRADE_MODE
-- TRAF_MODE -> PARA_TRANSF.TRAF_CODE
-- TRANS_MODE -> PARA_TRANSAC.TRANS_MODE
-- WRAP_TYPE -> PARA_WRAP.WRAP_CODE
-- FEE_CURR / INSUR_CURR / OTHER_CURR -> PARA_CURR.CURR_CODE
-- DISTINATE_PORT / DESP_PORT_CODE -> PARA_PORT_LIN.PORT_CODE
-- ENTY_PORT_CODE -> PARA_ENTRYPORT.PORT_CODE
-- BILL_TYPE -> PARA_INVTTYPE.C_CODE
-- ============================================================

INSERT INTO "DEC_HEAD" (
    "AGENT_CODE", "AGENT_NAME", "APPR_NO", "BILL_NO", "CONTR_NO",
    "COP_CODE", "COP_NAME", "CUSTOM_MASTER", "CUT_MODE", "DATA_SOURCE",
    "DECL_TRN_REL", "DISTINATE_PORT", "EDI_ID", "ENTRY_ID", "ENTRY_TYPE",
    "FEE_CURR", "FEE_MARK", "FEE_RATE", "GROSS_WET", "IE_DATE",
    "IE_FLAG", "IE_PORT", "INPUTER_NAME", "INSUR_CURR", "INSUR_MARK",
    "INSUR_RATE", "LICENSE_NO", "MANUAL_NO", "NET_WT", "NOTE_S",
    "OTHER_CURR", "OTHER_MARK", "OTHER_RATE", "OWNER_CODE", "OWNER_NAME",
    "PACK_NO", "PARTENER_ID", "P_DATE", "PRE_ENTRY_ID", "RISK",
    "SEQ_NO", "TGD_NO", "TRADE_COUNTRY", "TRADE_MODE", "TRADE_CODE",
    "TRAF_MODE", "TRAF_NAME", "TRADE_NAME", "TRANS_MODE", "TYPE",
    "TYPIST_NO", "WRAP_TYPE", "CHK_SURETY", "BILL_TYPE", "COP_CODE_SCC",
    "TRADE_CO_SCC", "AGENT_CODE_SCC", "OWNER_CODE_SCC", "PROMISE_ITMES", "BUSINESS_ITEMS", "TRADE_AREA_CODE",
    "CHECK_FLOW", "TAX_AAMIN_MARK", "MARK_NO", "DESP_PORT_CODE", "ENTY_PORT_CODE",
    "GOODS_PLACE", "BL_NO", "INSP_ORG_CODE", "SPEC_DECL_FLAG", "PURP_ORG_CODE",
    "DESP_DATE", "CMPL_DSCHRG_DT", "CORRELATION_REASON_FLAG", "VSA_ORG_CODE", "ORIG_BOX_FLAG",
    "DECLARE_NAME", "NO_OTHER_PACK", "ORG_CODE", "OVERSEAS_CONSIGNOR_CODE", "OVERSEAS_CONSIGNOR_CNAME",
    "OVERSEAS_CONSIGNOR_ENAME", "OVERSEAS_CONSIGNOR_ADDR", "OVERSEAS_CONSIGNEE_CODE", "OVERSEAS_CONSIGNEE_ENAME",
    "DOMESTIC_CONSIGNEE_ENAME", "CORRELATION_NO", "EDI_REMARK", "EDI_REMARK2",
    "TRADE_CIQ_CODE", "OWNER_CIQ_CODE", "DECL_CIQ_CODE"
)
SELECT
    '3301960001', '杭州测试报关有限公司', 'APPR202605060001', 'BL202605060001', 'HT202605060001',
    'TESTCIT01', '单一窗口测试录入单位',
    (SELECT "CUSTOMS_CODE" FROM "PARA_CUSTOMS_REL" WHERE LENGTH("CUSTOMS_CODE") <= 4 AND ROWNUM = 1),
    COALESCE((SELECT "CUT_MODE" FROM "PARA_LEVYTYPE" WHERE "CUT_MODE" = '101' AND ROWNUM = 1),
             (SELECT "CUT_MODE" FROM "PARA_LEVYTYPE" WHERE LENGTH("CUT_MODE") <= 3 AND ROWNUM = 1)),
    '00000',
    '0',
    (SELECT "PORT_CODE" FROM "PARA_PORT_LIN" WHERE LENGTH("PORT_CODE") <= 6 AND ROWNUM = 1),
    '1', 'E202605060000001', '0',
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'USD' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    '1', 1250.00000, 1200.50000, TO_DATE('2026-05-06', 'YYYY-MM-DD'),
    'I',
    (SELECT "CUSTOMS_CODE" FROM "PARA_CUSTOMS_REL" WHERE LENGTH("CUSTOMS_CODE") <= 4 AND ROWNUM = 1),
    '测试录入员',
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'USD' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    '1', 80.00000, 'LIC2026050601', 'B12345678901', 1000.00000, '单一窗口测试数据，参数字段来自 PARA 表',
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'CNY' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    '3', 20.00000, '91330100TEST0001', '杭州测试收货有限公司',
    10, '测试申报人', TO_DATE('2026-05-06', 'YYYY-MM-DD'), 'TST000001', '0',
    'TESTSEQ2026050601', 'TGD202605060001',
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 3 AND ROWNUM = 1)),
    COALESCE((SELECT "TRADE_MODE" FROM "PARA_TRADE" WHERE "TRADE_MODE" = '0110' AND ROWNUM = 1),
             (SELECT "TRADE_MODE" FROM "PARA_TRADE" WHERE LENGTH("TRADE_MODE") <= 4 AND ROWNUM = 1)),
    '91330100TEST0001',
    COALESCE((SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE "TRAF_CODE" = '2' AND ROWNUM = 1),
             (SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE LENGTH("TRAF_CODE") <= 1 AND ROWNUM = 1)),
    '测试运输工具',
    '杭州测试收货有限公司',
    COALESCE((SELECT "TRANS_MODE" FROM "PARA_TRANSAC" WHERE "TRANS_MODE" = '1' AND ROWNUM = 1),
             (SELECT "TRANS_MODE" FROM "PARA_TRANSAC" WHERE LENGTH("TRANS_MODE") <= 1 AND ROWNUM = 1)),
    '      ',
    'IC202605060001',
    COALESCE((SELECT "WRAP_CODE" FROM "PARA_WRAP" WHERE "WRAP_CODE" = '22' AND ROWNUM = 1),
             (SELECT "WRAP_CODE" FROM "PARA_WRAP" WHERE LENGTH("WRAP_CODE") <= 2 AND ROWNUM = 1)),
    '0',
    (SELECT "C_CODE" FROM "PARA_INVTTYPE" WHERE LENGTH("C_CODE") <= 1 AND ROWNUM = 1),
    '91330100TEST0001',
    '91330100TEST0001', '91330100TEST0001', '91330100TEST0001', '00000', '00000',
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 3 AND ROWNUM = 1)),
    '0', '0', 'N/M', (SELECT "PORT_CODE" FROM "PARA_PORT_LIN" WHERE LENGTH("PORT_CODE") <= 8 AND ROWNUM = 1),
    (SELECT "PORT_CODE" FROM "PARA_ENTRYPORT" WHERE LENGTH("PORT_CODE") <= 8 AND ROWNUM = 1),
    '杭州综合保税区测试仓库', 'BL202605060001', NULL, '0000000000',
    (SELECT "CUSTOMS_CODE" FROM "PARA_CUSTOMS_REL" WHERE LENGTH("CUSTOMS_CODE") <= 4 AND ROWNUM = 1),
    TO_DATE('2026-05-01', 'YYYY-MM-DD'), TO_DATE('2026-05-05', 'YYYY-MM-DD'), '01', NULL, '0',
    '张三', '0', NULL, 'OVERSEAS001', '境外测试发货人',
    'OVERSEAS TEST SHIPPER', 'No.1 Test Road', 'OVERSEAS002', 'OVERSEAS TEST CONSIGNEE',
    'HANGZHOU TEST CONSIGNEE', 'REL202605060001', 'EDI测试备注', 'EDI测试备注2',
    'CIQ0000001', 'CIQ0000002', 'CIQ0000003'
FROM DUAL;

-- ============================================================
-- 报关单商品表体：DEC_LIST
-- 参数来源：
-- CODE_TS / G_NAME -> PARA_COMPLEX.CODE_T_S / PARA_COMPLEX.G_NAME
-- DUTY_MODE -> PARA_LEVYMODE.DUTY_MODE
-- FIRST_UNIT / G_UNIT / SECOND_UNIT -> PARA_UNIT.UNIT_CODE
-- ORIGIN_COUNTRY / DESTINATION_COUNTRY -> PARA_COUNTRY.COUNTRY_CO
-- TRADE_CURR -> PARA_CURR.CURR_CODE
-- DISTRICT_CODE -> PARA_DISTRICT_REL.DISTRICT_CODE
-- ORIG_PLACE_CODE -> PARA_ORIGPLACE.C_CODE
-- PURPOSE -> PARA_PURPOSE.C_CODE
-- GOODS_ATTR -> PARA_GOODS_ATTR.ATTR_CODE
-- DEST_CODE -> PARA_DEST.DEST_CODE
-- ============================================================

INSERT INTO "DEC_LIST" (
    "DEC_HEAD_ID", "CLASS_MARK", "CODE_TS", "CONTR_ITEM", "DECL_PRICE",
    "DECL_TOTAL", "DUTY_MODE", "EXG_NO", "EXG_VERSION", "FACTOR",
    "FIRST_UNIT", "FIRST_QTY", "G_UNIT", "G_MODEL", "G_NAME",
    "G_NO", "G_QTY", "ORIGIN_COUNTRY", "SECOND_UNIT", "SECOND_QTY",
    "TRADE_CURR", "USE_TO", "WORK_USD", "DESTINATION_COUNTRY", "CIQ_CODE",
    "DECL_GOODS_ENAME", "ORIG_PLACE_CODE", "PURPOSE", "PROD_VALID_DT", "PROD_QGP",
    "GOODS_ATTR", "STUFF", "UNCODE", "DANG_NAME", "DANG_PACK_TYPE",
    "DANG_PACK_SPEC", "ENG_MAN_ENT_CNM", "NO_DANG_FLAG", "DEST_CODE", "GOODS_SPEC",
    "GOODS_MODEL", "GOODS_BRAND", "PRODUCE_DATE", "PROD_BATCH_NO", "DISTRICT_CODE",
    "CIQ_NAME", "MNUFCTR_REG_NO", "MNUFCTR_REG_NAME", "RCEP_ORIG_PLACE_CODE", "CONTROL_EXPLAIN_CODE"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    '0',
    (SELECT "CODE_T_S" FROM "PARA_COMPLEX" WHERE LENGTH("CODE_T_S") <= 10 AND ROWNUM = 1),
    1, 25.5000, 2550.0000,
    COALESCE((SELECT "DUTY_MODE" FROM "PARA_LEVYMODE" WHERE "DUTY_MODE" = '1' AND ROWNUM = 1),
             (SELECT "DUTY_MODE" FROM "PARA_LEVYMODE" WHERE LENGTH("DUTY_MODE") <= 1 AND ROWNUM = 1)),
    'EXG0001', 1, 1.000,
    COALESCE((SELECT "UNIT_CODE" FROM "PARA_UNIT" WHERE "UNIT_CODE" = '035' AND ROWNUM = 1),
             (SELECT "UNIT_CODE" FROM "PARA_UNIT" WHERE LENGTH("UNIT_CODE") <= 3 AND ROWNUM = 1)),
    100.00000,
    COALESCE((SELECT "UNIT_CODE" FROM "PARA_UNIT" WHERE "UNIT_CODE" = '035' AND ROWNUM = 1),
             (SELECT "UNIT_CODE" FROM "PARA_UNIT" WHERE LENGTH("UNIT_CODE") <= 3 AND ROWNUM = 1)),
    '品牌:TEST;规格:标准测试型号',
    COALESCE((SELECT SUBSTR("G_NAME", 1, 255) FROM "PARA_COMPLEX" WHERE "G_NAME" IS NOT NULL AND LENGTH("CODE_T_S") <= 10 AND ROWNUM = 1),
             '测试商品'),
    1, 100.00000,
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 3 AND ROWNUM = 1)),
    (SELECT "UNIT_CODE" FROM "PARA_UNIT" WHERE LENGTH("UNIT_CODE") <= 3 AND ROWNUM = 1),
    0.00000,
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'USD' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    '11', 2550.0000,
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 3 AND ROWNUM = 1)),
    '9999999999', 'TEST GOODS',
    (SELECT "C_CODE" FROM "PARA_ORIGPLACE" WHERE LENGTH("C_CODE") <= 50 AND ROWNUM = 1),
    (SELECT "C_CODE" FROM "PARA_PURPOSE" WHERE LENGTH("C_CODE") <= 4 AND ROWNUM = 1),
    '2027-05-06', '12个月',
    COALESCE((SELECT "ATTR_CODE" FROM "PARA_GOODS_ATTR" WHERE "ATTR_CODE" = '19' AND ROWNUM = 1),
             (SELECT "ATTR_CODE" FROM "PARA_GOODS_ATTR" WHERE LENGTH("ATTR_CODE") <= 20 AND ROWNUM = 1)),
    '测试材质', NULL, NULL, NULL,
    NULL, '测试生产企业', '0',
    (SELECT "DEST_CODE" FROM "PARA_DEST" WHERE LENGTH("DEST_CODE") <= 8 AND ROWNUM = 1),
    '测试规格', '测试型号', '测试品牌', '2026-04-20', 'BATCH2026050601',
    (SELECT "DISTRICT_CODE" FROM "PARA_DISTRICT_REL" WHERE LENGTH("DISTRICT_CODE") <= 5 AND ROWNUM = 1),
    '测试检验检疫名称', 'MFG20260506', '测试制造商',
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 3 AND ROWNUM = 1)),
    '0001'
FROM DUAL;

-- ============================================================
-- 报关单关联子表
-- ============================================================

INSERT INTO "DEC_CONTAINER" (
    "DEC_HEAD_ID", "DEC_LIST_ID", "CONTAINER_ID", "CONTAINER_MD", "GOODS_NO",
    "LCL_FLAG", "GOODS_CONTA_WT", "CONTAINER_WT"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "ID" FROM "DEC_LIST" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    'TSTU1234567', '40GP', '1', '0', 1000.00000, 2200.00000
FROM DUAL;

INSERT INTO "DEC_LICENSE_DOCUS" ("DEC_HEAD_ID", "DOCU_CODE", "CERT_CODE")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "CERT_CO" FROM "PARA_CERT" WHERE LENGTH("CERT_CO") <= 1 AND ROWNUM = 1),
    'CERT202605060001'
FROM DUAL;

INSERT INTO "DEC_REQUEST_CERT" ("DEC_HEAD_ID", "APP_CERT_CODE", "APPL_ORI", "APPL_COPY_QUAN")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "CERT_CO" FROM "PARA_CERT" WHERE LENGTH("CERT_CO") <= 50 AND ROWNUM = 1),
    '1', '1'
FROM DUAL;

INSERT INTO "DEC_GOODS_LIMIT" (
    "DEC_HEAD_ID", "DEC_LIST_ID", "GOODS_NO", "LIC_TYPE_CODE", "LICENCE_NO",
    "LIC_WRTOF_DETAIL_NO", "LIC_WRTOF_QTY", "LIC_WRTOF_QTY_UNIT"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "ID" FROM "DEC_LIST" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    1,
    (SELECT "CERT_CO" FROM "PARA_CERT" WHERE LENGTH("CERT_CO") <= 5 AND ROWNUM = 1),
    'LIC202605060001',
    '0001', '100',
    COALESCE((SELECT "UNIT_CODE" FROM "PARA_UNIT" WHERE "UNIT_CODE" = '035' AND ROWNUM = 1),
             (SELECT "UNIT_CODE" FROM "PARA_UNIT" WHERE LENGTH("UNIT_CODE") <= 3 AND ROWNUM = 1))
FROM DUAL;

INSERT INTO "DEC_GOODS_LIMIT_VIN" (
    "DEC_HEAD_ID", "DEC_GOODS_LIMIT_ID", "LICENCE_NO", "LIC_TYPE_CODE", "VIN_NO",
    "BILL_LAD_DATE", "QUALITY_QGP", "MOTOR_NO", "VIN_CODE", "CHASSIS_NO",
    "INVOICE_NUM", "PROD_CNNM", "PROD_ENNM", "MODEL_EN", "PRICE_PER_UNIT", "INVOICE_NO"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "ID" FROM "DEC_GOODS_LIMIT" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    'LIC202605060001',
    (SELECT "CERT_CO" FROM "PARA_CERT" WHERE LENGTH("CERT_CO") <= 5 AND ROWNUM = 1),
    'LTESTVIN20260506001',
    TO_DATE('2026-05-06', 'YYYY-MM-DD'), '合格', 'MOTOR20260506', 'VIN20260506000000001', 'CHASSIS001',
    1.00000, '测试车辆产品', 'TEST VEHICLE', 'MODEL TEST', '25500.00', 'INV202605060001'
FROM DUAL;

INSERT INTO "DEC_OTHER_PACK" ("DEC_HEAD_ID", "PACK_QTY", "PACK_TYPE")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    10.00000,
    COALESCE((SELECT "WRAP_CODE" FROM "PARA_WRAP" WHERE "WRAP_CODE" = '22' AND ROWNUM = 1),
             (SELECT "WRAP_CODE" FROM "PARA_WRAP" WHERE LENGTH("WRAP_CODE") <= 2 AND ROWNUM = 1))
FROM DUAL;

INSERT INTO "DEC_COP_LIMIT" ("DEC_HEAD_ID", "ENT_QUALIF_NO", "ENT_QUALIF_TYPE_CODE")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    'ENTQUAL202605060001',
    (SELECT "CERT_CO" FROM "PARA_CERT" WHERE LENGTH("CERT_CO") <= 5 AND ROWNUM = 1)
FROM DUAL;

INSERT INTO "DEC_USER" ("DEC_HEAD_ID", "USE_ORG_PERSON_CODE", "USE_ORG_PERSON_TEL")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    'USER202605060001', '13800000000'
FROM DUAL;

INSERT INTO "DEC_MARK_LOB" ("DEC_HEAD_ID", "ATTACH_NAME", "ATTACH_TYPE", "ATTACHMENT")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    '测试附件.png', 'png', EMPTY_BLOB()
FROM DUAL;

INSERT INTO "DEC_FREE_TXT" (
    "DEC_HEAD_ID", "BON_NO", "CUS_FIE", "DEC_BP_NO", "DEC_NO",
    "REL_ID", "REL_MAN_NO", "VOY_NO"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    'BON202605060001', 'CUSFIE01', 'BP202605060001', 'DEC2026050601',
    'REL202605060001', 'B12345678901', 'VOY202605060001'
FROM DUAL;

INSERT INTO "DEC_SIGN" (
    "DEC_HEAD_ID", "OPER_TYPE", "IC_CODE", "OPER_NAME", "COP_CODE",
    "CLIENT_SEQ_NO", "SIGN", "SIGN_DATE", "HOST_ID", "CERTIFICATE",
    "DOMAIN_ID", "NOTE", "BILL_SEQ_NO"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    '1', 'IC2605060001', '测试签名人', '91330100TEST0001',
    'CS20260506000001', 'TEST_SIGNATURE', CURRENT_TIMESTAMP, 'HOST000001', 'CERT202605060001',
    '1', '测试签名数据', 'BS20260506000001'
FROM DUAL;

-- ============================================================
-- 转关运输业务子表
-- ============================================================

INSERT INTO "TRN_HEAD" (
    "DEC_HEAD_ID", "TRN_PRE_ID", "TRANS_NO", "TURN_NO", "NATIVE_TRAF_MODE",
    "TRAF_CUSTOMS_NO", "NATIVE_SHIP_NAME", "NATIVE_VOYAGE_NO", "CONTRACTOR_NAME", "CONTRACTOR_CODE",
    "TRANS_FLAG", "VALID_TIME", "E_SEAL_FLAG", "NOTES", "TRN_TYPE", "APPL_CODE_SCC"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    'TRNPRE20260506001', 'TRANS2026050601', 'TURN20260506001',
    COALESCE((SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE "TRAF_CODE" = '2' AND ROWNUM = 1),
             (SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE LENGTH("TRAF_CODE") <= 1 AND ROWNUM = 1)),
    'TRAF202605001', '测试船舶', 'VY202605060001', '杭州测试承运企业', '3301960001',
    '01', TO_DATE('2026-12-31', 'YYYY-MM-DD'), '0', '转关测试数据', '1', '91330100TEST0001'
FROM DUAL;

INSERT INTO "TRN_LIST" ("TRN_HEAD_ID", "TRAF_MODE", "SHIP_ID", "SHIP_NAME_EN", "VOYAGE_NO", "BILL_NO", "IE_DATE")
SELECT
    (SELECT "ID" FROM "TRN_HEAD" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    COALESCE((SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE "TRAF_CODE" = '2' AND ROWNUM = 1),
             (SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE LENGTH("TRAF_CODE") <= 1 AND ROWNUM = 1)),
    'SHIP202605060001', 'TEST SHIP', 'VY202605060001', 'BL202605060001', TO_DATE('2026-05-06', 'YYYY-MM-DD')
FROM DUAL;

INSERT INTO "TRN_CONTAINER" (
    "TRN_HEAD_ID", "TRN_LIST_ID", "CONTA_NO", "CONTA_SN", "CONTA_MODEL",
    "SEAL_NO", "TRANS_NAME", "TRANS_WEIGHT", "SEAL_QTY"
)
SELECT
    (SELECT "ID" FROM "TRN_HEAD" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    (SELECT "ID" FROM "TRN_LIST" WHERE "TRN_HEAD_ID" = (SELECT "ID" FROM "TRN_HEAD" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1) AND ROWNUM = 1),
    'TSTU1234567', 1, '40GP', 'SEAL202605060001', '测试运输', 1200.00000, '1'
FROM DUAL;

INSERT INTO "TRN_CONTA_GOODS_LIST" (
    "TRN_CONTAINER_ID", "TRN_LIST_ID", "G_NO", "CONTA_NO", "CONTA_GOODS_COUNT", "CONTA_GOODS_WEIGHT"
)
SELECT
    (SELECT "ID" FROM "TRN_CONTAINER" WHERE "TRN_HEAD_ID" = (SELECT "ID" FROM "TRN_HEAD" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1) AND ROWNUM = 1),
    (SELECT "ID" FROM "TRN_LIST" WHERE "TRN_HEAD_ID" = (SELECT "ID" FROM "TRN_HEAD" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1) AND ROWNUM = 1),
    1, 'TSTU1234567', 10, 1000.00000
FROM DUAL;

-- ============================================================
-- 补充申报、电子单证、原产地关系、税单等
-- ============================================================

INSERT INTO "DEC_SUPPLEMENT" (
    "DEC_HEAD_ID", "DEC_LIST_ID", "G_NO", "SUP_TYPE", "BRAND_CN",
    "BRAND_EN", "BUYER", "BUYER_CONTACT", "BUYER_ADDR", "BUYER_TEL",
    "SELLER", "SELLER_CONTACT", "SELLER_ADDR", "SELLER_TEL", "FACTORY",
    "FACTORY_CONTACT", "FACTORY_ADDR", "FACTORY_TEL", "CONTR_NO", "CONTR_DATE",
    "INVOICE_NO", "INVOICE_DATE", "I_BAB_REL", "I_PRICE_EFFECT", "I_PRICE_CLOSE",
    "I_OTHER_LIMITED", "I_OTHER_EFFECT", "I_NOTE1", "I_IS_USEFEE", "I_IS_PROFIT",
    "I_NOTE2", "CURR", "INVOICE_PRICE", "INVOICE_AMOUNT", "INVOICE_NOTE",
    "GOODS_PRICE", "GOODS_AMOUNT", "GOODS_NOTE", "I_COMMISSION_PRICE", "I_COMMISSION_AMOUNT",
    "I_COMMISSION_NOTE", "I_CONTAINER_PRICE", "I_CONTAINER_AMOUNT", "I_CONTAINER_NOTE", "I_PACK_PRICE",
    "I_PACK_AMOUNT", "I_PACK_NOTE", "I_PART_PRICE", "I_PART_AMOUNT", "I_PART_NOTE",
    "I_TOOL_PRICE", "I_TOOL_AMOUNT", "I_TOOL_NOTE", "I_LOSS_PRICE", "I_LOSS_AMOUNT",
    "I_LOSS_NOTE", "I_DESIGN_PRICE", "I_DESIGN_AMOUNT", "I_DESIGN_NOTE", "I_USEFEE_PRICE",
    "I_USEFEE_AMOUNT", "I_USEFEE_NOTE", "I_PROFIT_PRICE", "I_PROFIT_AMOUNT", "I_PROFIT_NOTE",
    "I_FEE_PRICE", "I_FEE_AMOUNT", "I_FEE_NOTE", "I_OTHER_PRICE", "I_OTHER_AMOUNT",
    "I_OTHER_NOTE", "I_INSUR_PRICE", "I_INSUR_AMOUNT", "I_INSUR_NOTE", "E_IS_DUTY_DEL",
    "G_NAME_OTHER", "CODE_TS_OTHER", "IS_CLASS_DECISION", "DECISION_NO", "CODE_TS_DECISION",
    "DECISION_CUS", "IS_SAMPLE_TEST", "G_OPTIONS", "TRAF_MODE", "IS_DIRECT_TRAF",
    "TRANSIT_COUNTRY", "DEST_PORT", "DECL_PORT", "BILL_NO", "ORIGIN_COUNTRY",
    "ORIGIN_MARK", "CERT_COUNTRY", "CERT_NO", "CERT_STANDARD", "OTHER_NOTE",
    "IS_SECRET", "AGENT_TYPE", "DECL_ADDR", "DECL_POST", "DECL_TEL"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "ID" FROM "DEC_LIST" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    1, '1', '测试品牌', 'TEST BRAND', '测试买方', '买方联系人', '买方地址', '13800000001',
    '测试卖方', '卖方联系人', '卖方地址', '13800000002', '测试工厂',
    '工厂联系人', '工厂地址', '13800000003', 'HT202605060001', TO_DATE('2026-05-01', 'YYYY-MM-DD'),
    'INV202605060001', TO_DATE('2026-05-02', 'YYYY-MM-DD'), '0', '0', '0',
    '0', '0', '补充申报测试说明', '0', '0',
    '补充申报测试备注',
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'USD' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    25.5000, 2550.00, '发票价格说明',
    25.5000, 2550.00, '货物价格说明', 0.0000, 0.00,
    '佣金说明', 0.0000, 0.00, '容器说明', 0.0000,
    0.00, '包装说明', 0.0000, 0.00, '零部件说明',
    0.0000, 0.00, '工具说明', 0.0000, 0.00,
    '损耗说明', 0.0000, 0.00, '设计说明', 0.0000,
    0.00, '特许权说明', 0.0000, 0.00, '收益说明',
    0.0000, 0.00, '费用说明', 0.0000, 0.00,
    '其他说明', 0.0000, 0.00, '保险说明', '0',
    '测试其他商品名称',
    (SELECT "CODE_T_S" FROM "PARA_COMPLEX" WHERE LENGTH("CODE_T_S") <= 15 AND ROWNUM = 1),
    '0', 'DECISION202605060001',
    (SELECT "CODE_T_S" FROM "PARA_COMPLEX" WHERE LENGTH("CODE_T_S") <= 15 AND ROWNUM = 1),
    (SELECT "CUSTOMS_CODE" FROM "PARA_CUSTOMS_REL" WHERE LENGTH("CUSTOMS_CODE") <= 4 AND ROWNUM = 1),
    '0', '00000',
    COALESCE((SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE "TRAF_CODE" = '2' AND ROWNUM = 1),
             (SELECT "TRAF_CODE" FROM "PARA_TRANSF" WHERE LENGTH("TRAF_CODE") <= 1 AND ROWNUM = 1)),
    '0',
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 20 AND ROWNUM = 1)),
    (SELECT "CUSTOMS_CODE" FROM "PARA_CUSTOMS_REL" WHERE LENGTH("CUSTOMS_CODE") <= 4 AND ROWNUM = 1),
    (SELECT "CUSTOMS_CODE" FROM "PARA_CUSTOMS_REL" WHERE LENGTH("CUSTOMS_CODE") <= 4 AND ROWNUM = 1),
    'BL202605060001',
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 3 AND ROWNUM = 1)),
    'CN',
    COALESCE((SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE "COUNTRY_CO" = '142' AND ROWNUM = 1),
             (SELECT "COUNTRY_CO" FROM "PARA_COUNTRY" WHERE LENGTH("COUNTRY_CO") <= 30 AND ROWNUM = 1)),
    'ECO202605060001', '1', '其他补充说明',
    '0', '1', '杭州市测试路1号', '310000', '057100000000'
FROM DUAL;

INSERT INTO "EDOC_RELATION" (
    "DEC_HEAD_ID", "EDOC_ID", "EDOC_CODE", "EDOC_FOMAT_TYPE", "OP_NOTE",
    "EDOC_COP_ID", "EDOC_OWNER_CODE", "SIGN_UNIT", "SIGN_TIME", "EDOC_OWNER_NAME",
    "EDOC_SIZE", "G_NO_STR"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    'EDOC202605060001',
    (SELECT "CERT_CO" FROM "PARA_CERT" WHERE LENGTH("CERT_CO") <= 8 AND ROWNUM = 1),
    '01', '电子单证测试',
    'EDOCCOP202605060001', '3301960001', '3301960001', '20260506120000000', '杭州测试报关有限公司',
    '1024', '1'
FROM DUAL;

INSERT INTO "ECO_RELATION" (
    "DEC_HEAD_ID", "DEC_LIST_ID", "CERT_TYPE", "DEC_G_NO", "ECO_CERT_NO", "ECO_G_NO", "EXTEND_FILED"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "ID" FROM "DEC_LIST" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    COALESCE((SELECT 'Y' || SUBSTR("AGREEMENT_CODE", 1, 2) FROM "PARA_AGREEMENT_RATE" WHERE "AGREEMENT_CODE" IS NOT NULL AND ROWNUM = 1), 'Y01'),
    '1', 'CECO202605060001', '1', '优惠贸易协定享惠测试'
FROM DUAL;

INSERT INTO "SDD_TAX" (
    "DEC_HEAD_ID", "FILE_NAME", "SEQ_NO", "IE_FLAG", "DECL_PORT",
    "D_DATE", "TRADE_CO", "TRADE_NAME", "IN_RATIO", "TRADE_MODE",
    "CUT_MODE", "TRANS_MODE", "FEE_MARK", "FEE_CURR", "FEE_RATE",
    "INSUR_MARK", "INSUR_RATE", "OTHER_MARK", "OTHER_CURR", "OTHER_RATE",
    "MANUAL_NO", "TRADE_CO_SCC", "GROSS_WT", "NOTE_S", "LEGAL_LIABILITY",
    "SIGN", "MESS_ID", "CERT_SEQ_NO", "STATUS"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    'TAX202605060001', 'TESTSEQ2026050601', 'I',
    (SELECT "CUSTOMS_CODE" FROM "PARA_CUSTOMS_REL" WHERE LENGTH("CUSTOMS_CODE") <= 4 AND ROWNUM = 1),
    '2026-05-06', '3301960001', '杭州测试收货有限公司', 0.0000000,
    COALESCE((SELECT "TRADE_MODE" FROM "PARA_TRADE" WHERE "TRADE_MODE" = '0110' AND ROWNUM = 1),
             (SELECT "TRADE_MODE" FROM "PARA_TRADE" WHERE LENGTH("TRADE_MODE") <= 4 AND ROWNUM = 1)),
    COALESCE((SELECT "CUT_MODE" FROM "PARA_LEVYTYPE" WHERE "CUT_MODE" = '101' AND ROWNUM = 1),
             (SELECT "CUT_MODE" FROM "PARA_LEVYTYPE" WHERE LENGTH("CUT_MODE") <= 3 AND ROWNUM = 1)),
    COALESCE((SELECT "TRANS_MODE" FROM "PARA_TRANSAC" WHERE "TRANS_MODE" = '1' AND ROWNUM = 1),
             (SELECT "TRANS_MODE" FROM "PARA_TRANSAC" WHERE LENGTH("TRANS_MODE") <= 1 AND ROWNUM = 1)),
    '1',
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'USD' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    1250.0000000, '1', 80.0000000, '3',
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'CNY' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    20.0000000, 'B12345678901', '91330100TEST0001', 1200.5000000,
    '报税单测试数据', '本单位承诺测试数据真实有效', 'TEST_TAX_SIGNATURE',
    'MESS202605060001', 'CERTSEQ202605060001', '1'
FROM DUAL;

INSERT INTO "DEC_RISK" ("DEC_HEAD_ID", "RISK", "SIGN", "SIGN_DATE", "NOTE")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    '0', 'TEST_RISK_SIGN', CURRENT_TIMESTAMP, '风险评估测试'
FROM DUAL;

INSERT INTO "DEC_COP_PROMISE" ("DEC_HEAD_ID", "DECLARATIO_MATERIAL_CODE")
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    '101040'
FROM DUAL;

INSERT INTO "DEC_ROYALTY_FEE" (
    "DEC_HEAD_ID", "PRICE_PRE_DETERMIN_NO", "TAX_ROYALTY_DECL_TYPE", "CONTRACT_NO", "AUTHORIZER",
    "AUTHORIZED_PERSON", "PAY_TYPE", "PAY_TIME", "PAY_PERIOD", "EFFECTIVE_DATE_TIME",
    "EXPIRATION_DATE_TIME", "ROYALTY_AMOUNT", "CURR", "ROYALTY_FEE_TYPE", "EDOC_TYPE",
    "STATMENT", "IS_SECRET", "IS_CUS_AUDIT", "IS_CUS_PRICE_PRE_DETERMIN", "ISSUE_DATE_TIME",
    "PERIOD_START_DATE", "PERIOD_END_DATE"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    'PRICEPRE2026050601', '0', 'ROYALTY-HT-20260506', '境外测试授权方',
    '杭州测试被授权方', '0', '2026-05-06', 12, '2026-01-01',
    TO_DATE('2036-01-01', 'YYYY-MM-DD'), 1000.00,
    COALESCE((SELECT "CURR_CODE" FROM "PARA_CURR" WHERE "CURR_CODE" = 'USD' AND ROWNUM = 1),
             (SELECT "CURR_CODE" FROM "PARA_CURR" WHERE LENGTH("CURR_CODE") <= 3 AND ROWNUM = 1)),
    '1000', '111111',
    '特许权使用费测试说明', '0', '0', '0', '2026-01-01',
    '2026-01-01', '2026-12-31'
FROM DUAL;

INSERT INTO "DEC_TP_ACCESS" (
    "DEC_HEAD_ID", "TRANSITION_APPLY", "TRANSITION_SITE", "CONDITIONAL_LIFTOFF_APPLY", "PORT_DEST_MERGE_CHECK_APPLY"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    '1', 'SITE2026001', '0', '0'
FROM DUAL;

INSERT INTO "DEC_CONTROL_MODEL" (
    "DEC_HEAD_ID", "DEC_LIST_ID", "ELEMENT_NO", "ELEMENT_VALUE", "DECLARATION_CATEGORY_CODE"
)
SELECT
    (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1),
    (SELECT "ID" FROM "DEC_LIST" WHERE "DEC_HEAD_ID" = (SELECT "ID" FROM "DEC_HEAD" WHERE "PRE_ENTRY_ID" = 'TST000001' AND ROWNUM = 1) AND ROWNUM = 1),
    '1', '禁限管制申报要素测试值', '0001'
FROM DUAL;

COMMIT;
