-- 达梦数据库版本：单一窗口检验检疫签证申报要素表
-- 用于保存检验检疫签证申报要素弹窗中的证书选择和补充信息。

CREATE TABLE "DEC_CIQ_VISA" (
    "ID" BIGINT IDENTITY(1,1) NOT NULL,
    "DEC_HEAD_ID" BIGINT NOT NULL,
    "DEC_LIST_ID" BIGINT,
    "CERT_CODE" VARCHAR2(50),
    "CERT_NAME" VARCHAR2(200),
    "CERT_ORIGINAL_COUNT" VARCHAR2(50),
    "CERT_COPY_COUNT" VARCHAR2(50),
    "DOMESTIC_CONSIGNEE_ENAME" VARCHAR2(400),
    "OVERSEAS_CONSIGNOR_CNAME" VARCHAR2(150),
    "OVERSEAS_CONSIGNOR_ADDR" VARCHAR2(100),
    "CMPL_DSCHRG_DT" DATE,
    "DECL_GOODS_ENAME" VARCHAR2(100),
    CONSTRAINT "PK_DEC_CIQ_VISA" PRIMARY KEY ("ID")
);

CREATE INDEX "IDX_DEC_CIQ_VISA_HEAD_LIST" ON "DEC_CIQ_VISA" ("DEC_HEAD_ID", "DEC_LIST_ID");
CREATE INDEX "IDX_DEC_CIQ_VISA_CERT_CODE" ON "DEC_CIQ_VISA" ("CERT_CODE");

COMMENT ON TABLE "DEC_CIQ_VISA" IS '检验检疫签证申报要素';
COMMENT ON COLUMN "DEC_CIQ_VISA"."ID" IS '主键ID，达梦自增标识列';
COMMENT ON COLUMN "DEC_CIQ_VISA"."DEC_HEAD_ID" IS '报关单表头ID，父表关联ID';
COMMENT ON COLUMN "DEC_CIQ_VISA"."DEC_LIST_ID" IS '报关单商品表体ID，父表关联ID';
COMMENT ON COLUMN "DEC_CIQ_VISA"."CERT_CODE" IS '证书代码';
COMMENT ON COLUMN "DEC_CIQ_VISA"."CERT_NAME" IS '证书名称';
COMMENT ON COLUMN "DEC_CIQ_VISA"."CERT_ORIGINAL_COUNT" IS '正本数量';
COMMENT ON COLUMN "DEC_CIQ_VISA"."CERT_COPY_COUNT" IS '副本数量';
COMMENT ON COLUMN "DEC_CIQ_VISA"."DOMESTIC_CONSIGNEE_ENAME" IS '境内收发货人名称（外文）';
COMMENT ON COLUMN "DEC_CIQ_VISA"."OVERSEAS_CONSIGNOR_CNAME" IS '境外收发货人名称（中文）';
COMMENT ON COLUMN "DEC_CIQ_VISA"."OVERSEAS_CONSIGNOR_ADDR" IS '境外发货人地址';
COMMENT ON COLUMN "DEC_CIQ_VISA"."CMPL_DSCHRG_DT" IS '卸毕日期';
COMMENT ON COLUMN "DEC_CIQ_VISA"."DECL_GOODS_ENAME" IS '商品英文名称';

COMMIT;
