-- 达梦数据库版本（字段大写下划线命名）
CREATE TABLE "DOCUMENTS" (
                             "ID" BIGINT IDENTITY(1,1) NOT NULL,
                             "ORIGINAL_FILENAME" VARCHAR(200),
                             "FILENAME" VARCHAR(200),
                             "STORAGE_PATH" VARCHAR(500),
                             "STORAGE_TYPE" VARCHAR(30),
                             "FILE_SIZE" BIGINT,
                             "CONTENT_TYPE" VARCHAR(100),
                             "STATUS" VARCHAR(30),
                             "UPLOADED_AT" TIMESTAMP,
                             "STARTED_AT" TIMESTAMP,
                             "FINISHED_AT" TIMESTAMP,
                             "DEC_HEAD_ID" BIGINT,
                             "TASK_ID" VARCHAR(64),
                             "ERROR_MESSAGE" VARCHAR(1000),
                             CONSTRAINT "PK_DOCUMENTS" PRIMARY KEY ("ID")
);

CREATE INDEX "IDX_DOCUMENTS_TASK_ID" ON "DOCUMENTS" ("TASK_ID");
CREATE INDEX "IDX_DOCUMENTS_DEC_HEAD_ID" ON "DOCUMENTS" ("DEC_HEAD_ID");
CREATE INDEX "IDX_DOCUMENTS_STATUS" ON "DOCUMENTS" ("STATUS");

COMMENT ON TABLE "DOCUMENTS" IS '文档解析任务';
COMMENT ON COLUMN "DOCUMENTS"."ID" IS '主键ID，达梦自增标识列';
COMMENT ON COLUMN "DOCUMENTS"."ORIGINAL_FILENAME" IS '原始文件名称';
COMMENT ON COLUMN "DOCUMENTS"."FILENAME" IS '存储文件名称';
COMMENT ON COLUMN "DOCUMENTS"."STORAGE_PATH" IS '存储路径';
COMMENT ON COLUMN "DOCUMENTS"."STORAGE_TYPE" IS '存储类型';
COMMENT ON COLUMN "DOCUMENTS"."FILE_SIZE" IS '文件大小';
COMMENT ON COLUMN "DOCUMENTS"."CONTENT_TYPE" IS '文件MIME类型';
COMMENT ON COLUMN "DOCUMENTS"."STATUS" IS '处理状态：NOT_STARTED/PARSING/COMPLETED';
COMMENT ON COLUMN "DOCUMENTS"."UPLOADED_AT" IS '上传时间';
COMMENT ON COLUMN "DOCUMENTS"."STARTED_AT" IS '开始解析时间';
COMMENT ON COLUMN "DOCUMENTS"."FINISHED_AT" IS '解析完成时间';
COMMENT ON COLUMN "DOCUMENTS"."DEC_HEAD_ID" IS '报关单id';
COMMENT ON COLUMN "DOCUMENTS"."TASK_ID" IS '解析任务id';
COMMENT ON COLUMN "DOCUMENTS"."ERROR_MESSAGE" IS '错误信息';