-- XXL-JOB v2.4.0
-- Converted from MySQL to DM8.
-- Source: tables_xxl_job.sql
-- Table and column identifiers are normalized to uppercase and explicitly quoted for DM8.

DROP TABLE IF EXISTS "XXL_JOB_GROUP";
CREATE TABLE "XXL_JOB_GROUP" (
  "ID" INTEGER IDENTITY(1,1) NOT NULL,
  "APP_NAME" VARCHAR2(64) NOT NULL,
  -- MySQL varchar(12) uses character length; DM VARCHAR2 length is byte-sensitive, so widen this Chinese title field.
  "TITLE" VARCHAR2(64) NOT NULL,
  "ADDRESS_TYPE" TINYINT DEFAULT 0 NOT NULL,
  "ADDRESS_LIST" CLOB NULL,
  "UPDATE_TIME" TIMESTAMP NULL,
  CONSTRAINT "PK_XXL_JOB_GROUP" PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "XXL_JOB_GROUP"."APP_NAME" IS '执行器AppName';
COMMENT ON COLUMN "XXL_JOB_GROUP"."TITLE" IS '执行器名称';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';

SET IDENTITY_INSERT "XXL_JOB_GROUP" ON;
INSERT INTO "XXL_JOB_GROUP" ("ID", "APP_NAME", "TITLE", "ADDRESS_TYPE", "ADDRESS_LIST", "UPDATE_TIME") VALUES (1, 'xxl-job-executor-sample', '示例执行器', 0, NULL, '2025-02-10 13:49:04');
INSERT INTO "XXL_JOB_GROUP" ("ID", "APP_NAME", "TITLE", "ADDRESS_TYPE", "ADDRESS_LIST", "UPDATE_TIME") VALUES (2, 'jeecg-demo', '测试Demo模块', 0, NULL, '2025-02-10 13:49:04');
INSERT INTO "XXL_JOB_GROUP" ("ID", "APP_NAME", "TITLE", "ADDRESS_TYPE", "ADDRESS_LIST", "UPDATE_TIME") VALUES (3, 'jeecg-system', '系统System模块', 0, NULL, '2025-02-10 13:49:04');
SET IDENTITY_INSERT "XXL_JOB_GROUP" OFF;

DROP TABLE IF EXISTS "XXL_JOB_INFO";
CREATE TABLE "XXL_JOB_INFO" (
  "ID" INTEGER IDENTITY(1,1) NOT NULL,
  "JOB_GROUP" INTEGER NOT NULL,
  "JOB_DESC" VARCHAR2(255) NOT NULL,
  "ADD_TIME" TIMESTAMP NULL,
  "UPDATE_TIME" TIMESTAMP NULL,
  "AUTHOR" VARCHAR2(64) NULL,
  "ALARM_EMAIL" VARCHAR2(255) NULL,
  "SCHEDULE_TYPE" VARCHAR2(50) DEFAULT 'NONE' NOT NULL,
  "SCHEDULE_CONF" VARCHAR2(128) NULL,
  "MISFIRE_STRATEGY" VARCHAR2(50) DEFAULT 'DO_NOTHING' NOT NULL,
  "EXECUTOR_ROUTE_STRATEGY" VARCHAR2(50) NULL,
  "EXECUTOR_HANDLER" VARCHAR2(255) NULL,
  "EXECUTOR_PARAM" VARCHAR2(512) NULL,
  "EXECUTOR_BLOCK_STRATEGY" VARCHAR2(50) NULL,
  "EXECUTOR_TIMEOUT" INTEGER DEFAULT 0 NOT NULL,
  "EXECUTOR_FAIL_RETRY_COUNT" INTEGER DEFAULT 0 NOT NULL,
  "GLUE_TYPE" VARCHAR2(50) NOT NULL,
  "GLUE_SOURCE" CLOB NULL,
  "GLUE_REMARK" VARCHAR2(128) NULL,
  "GLUE_UPDATETIME" TIMESTAMP NULL,
  "CHILD_JOBID" VARCHAR2(255) NULL,
  "TRIGGER_STATUS" TINYINT DEFAULT 0 NOT NULL,
  "TRIGGER_LAST_TIME" BIGINT DEFAULT 0 NOT NULL,
  "TRIGGER_NEXT_TIME" BIGINT DEFAULT 0 NOT NULL,
  CONSTRAINT "PK_XXL_JOB_INFO" PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "XXL_JOB_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "XXL_JOB_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "XXL_JOB_INFO"."SCHEDULE_TYPE" IS '调度类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."SCHEDULE_CONF" IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."MISFIRE_STRATEGY" IS '调度过期策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_TIMEOUT" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."CHILD_JOBID" IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_STATUS" IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_LAST_TIME" IS '上次调度时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_NEXT_TIME" IS '下次调度时间';

SET IDENTITY_INSERT "XXL_JOB_INFO" ON;
INSERT INTO "XXL_JOB_INFO" ("ID", "JOB_GROUP", "JOB_DESC", "ADD_TIME", "UPDATE_TIME", "AUTHOR", "ALARM_EMAIL", "SCHEDULE_TYPE", "SCHEDULE_CONF", "MISFIRE_STRATEGY", "EXECUTOR_ROUTE_STRATEGY", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_BLOCK_STRATEGY", "EXECUTOR_TIMEOUT", "EXECUTOR_FAIL_RETRY_COUNT", "GLUE_TYPE", "GLUE_SOURCE", "GLUE_REMARK", "GLUE_UPDATETIME", "CHILD_JOBID", "TRIGGER_STATUS", "TRIGGER_LAST_TIME", "TRIGGER_NEXT_TIME") VALUES (1, 1, '测试任务1', '2018-11-03 22:21:31', '2024-08-21 22:30:30', 'XXL', '', 'CRON', '0 0 0 * * ? *', 'DO_NOTHING', 'FIRST', 'demoJob', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', TO_CLOB(''), 'GLUE代码初始化', '2018-11-03 22:21:31', '', 1, 1729353600000, 1739203200000);
INSERT INTO "XXL_JOB_INFO" ("ID", "JOB_GROUP", "JOB_DESC", "ADD_TIME", "UPDATE_TIME", "AUTHOR", "ALARM_EMAIL", "SCHEDULE_TYPE", "SCHEDULE_CONF", "MISFIRE_STRATEGY", "EXECUTOR_ROUTE_STRATEGY", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_BLOCK_STRATEGY", "EXECUTOR_TIMEOUT", "EXECUTOR_FAIL_RETRY_COUNT", "GLUE_TYPE", "GLUE_SOURCE", "GLUE_REMARK", "GLUE_UPDATETIME", "CHILD_JOBID", "TRIGGER_STATUS", "TRIGGER_LAST_TIME", "TRIGGER_NEXT_TIME") VALUES (2, 3, '测试jeecg xxljob', '2024-08-21 22:41:10', '2024-08-21 22:41:30', 'JEECG', '', 'CRON', '* * * * * ?', 'DO_NOTHING', 'FIRST', 'demoJob', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', TO_CLOB(''), 'GLUE代码初始化', '2024-08-21 22:41:10', '', 1, 1739166572000, 1739166573000);
SET IDENTITY_INSERT "XXL_JOB_INFO" OFF;

DROP TABLE IF EXISTS "XXL_JOB_LOCK";
CREATE TABLE "XXL_JOB_LOCK" (
  "LOCK_NAME" VARCHAR2(50) NOT NULL,
  CONSTRAINT "PK_XXL_JOB_LOCK" PRIMARY KEY ("LOCK_NAME")
);
COMMENT ON COLUMN "XXL_JOB_LOCK"."LOCK_NAME" IS '锁名称';

INSERT INTO "XXL_JOB_LOCK" ("LOCK_NAME") VALUES ('schedule_lock');
DROP TABLE IF EXISTS "XXL_JOB_LOG";
CREATE TABLE "XXL_JOB_LOG" (
  "ID" BIGINT IDENTITY(1,1) NOT NULL,
  "JOB_GROUP" INTEGER NOT NULL,
  "JOB_ID" INTEGER NOT NULL,
  "EXECUTOR_ADDRESS" VARCHAR2(255) NULL,
  "EXECUTOR_HANDLER" VARCHAR2(255) NULL,
  "EXECUTOR_PARAM" VARCHAR2(512) NULL,
  "EXECUTOR_SHARDING_PARAM" VARCHAR2(20) NULL,
  "EXECUTOR_FAIL_RETRY_COUNT" INTEGER DEFAULT 0 NOT NULL,
  "TRIGGER_TIME" TIMESTAMP NULL,
  "TRIGGER_CODE" INTEGER NOT NULL,
  "TRIGGER_MSG" CLOB NULL,
  "HANDLE_TIME" TIMESTAMP NULL,
  "HANDLE_CODE" INTEGER NOT NULL,
  "HANDLE_MSG" CLOB NULL,
  "ALARM_STATUS" TINYINT DEFAULT 0 NOT NULL,
  CONSTRAINT "PK_XXL_JOB_LOG" PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_SHARDING_PARAM" IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_MSG" IS '执行-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."ALARM_STATUS" IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';
CREATE INDEX "I_TRIGGER_TIME" ON "XXL_JOB_LOG" ("TRIGGER_TIME");
CREATE INDEX "I_HANDLE_CODE" ON "XXL_JOB_LOG" ("HANDLE_CODE");

SET IDENTITY_INSERT "XXL_JOB_LOG" ON;
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6618, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:09', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6619, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:10', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6620, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:11', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6621, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:12', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6622, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:13', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6623, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:14', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6624, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:15', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6625, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:16', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6626, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:17', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6627, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:18', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6628, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:19', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6629, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:20', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6630, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:21', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6631, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:22', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6632, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:23', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6633, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:24', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6634, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:25', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6635, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:26', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6636, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:27', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6637, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:28', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6638, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:29', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6639, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:30', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6640, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:31', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6641, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:32', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6642, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:33', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6643, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:34', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6644, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:35', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6645, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:36', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6646, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:37', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6647, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:38', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6648, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:39', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6649, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:40', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6650, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:41', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6651, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:42', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6652, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:43', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6653, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:44', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6654, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:45', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6655, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:46', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6656, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:47', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6657, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:48', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6658, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:49', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6659, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:50', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6660, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:51', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6661, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:52', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6662, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:53', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6663, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:54', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6664, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:55', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6665, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:56', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6666, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:57', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6667, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:58', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6668, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:47:59', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6669, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:00', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6670, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:01', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6671, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:02', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6672, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:03', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6673, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:04', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6674, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:05', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6675, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:06', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6676, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:07', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6677, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:08', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6678, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:09', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6679, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:10', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6680, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:11', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6681, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:12', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6682, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:13', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6683, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:14', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6684, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:15', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6685, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:16', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6686, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:17', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6687, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:18', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6688, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:19', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6689, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:20', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6690, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:21', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6691, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:22', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6692, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:23', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6693, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:24', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6694, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:25', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6695, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:26', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6696, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:27', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6697, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:28', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6698, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:29', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6699, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:30', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6700, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:31', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6701, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:32', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6702, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:33', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6703, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:34', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6704, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:35', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6705, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:36', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6706, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:37', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6707, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:38', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6708, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:39', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6709, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:40', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6710, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:41', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6711, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:42', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6712, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:43', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6713, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:44', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6714, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:45', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6715, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:46', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6716, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:47', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6717, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:48', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6718, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:49', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6719, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:50', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6720, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:51', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6721, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:52', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6722, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:53', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6723, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:54', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6724, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:55', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6725, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:56', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6726, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:57', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6727, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:58', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6728, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:48:59', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6729, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:00', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6730, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:01', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6731, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:02', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6732, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:03', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6733, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:04', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6734, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:05', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6735, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:06', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6736, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:07', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6737, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:08', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6738, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:09', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6739, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:10', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6740, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:11', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6741, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:12', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6742, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:13', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6743, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:14', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6744, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:15', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6745, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:16', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6746, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:17', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6747, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:18', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6748, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:19', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6749, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:20', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6750, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:21', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6751, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:22', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6752, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:23', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6753, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:24', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 2);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6754, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:25', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 0);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6755, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:26', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 0);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6756, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:27', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 0);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6757, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:28', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 0);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6758, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:29', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 0);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6759, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:30', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 0);
INSERT INTO "XXL_JOB_LOG" ("ID", "JOB_GROUP", "JOB_ID", "EXECUTOR_ADDRESS", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_SHARDING_PARAM", "EXECUTOR_FAIL_RETRY_COUNT", "TRIGGER_TIME", "TRIGGER_CODE", "TRIGGER_MSG", "HANDLE_TIME", "HANDLE_CODE", "HANDLE_MSG", "ALARM_STATUS") VALUES (6760, 3, 2, NULL, 'demoJob', '', NULL, 0, '2025-02-10 13:49:31', 500, TO_CLOB('任务触发类型：Cron触发<br>调度机器：192.168.1.11<br>执行器-注册方式：自动注册<br>执行器-地址列表：null<br>路由策略：第一个<br>阻塞处理策略：单机串行<br>任务超时时间：0<br>失败重试次数：0<br><br><span style="color:#00c0ef;" > >>>>>>>>>>>触发调度<<<<<<<<<<< </span><br>调度失败：执行器地址为空<br><br>'), NULL, 0, NULL, 0);
SET IDENTITY_INSERT "XXL_JOB_LOG" OFF;

DROP TABLE IF EXISTS "XXL_JOB_LOG_REPORT";
CREATE TABLE "XXL_JOB_LOG_REPORT" (
  "ID" INTEGER IDENTITY(1,1) NOT NULL,
  "TRIGGER_DAY" TIMESTAMP NULL,
  "RUNNING_COUNT" INTEGER DEFAULT 0 NOT NULL,
  "SUC_COUNT" INTEGER DEFAULT 0 NOT NULL,
  "FAIL_COUNT" INTEGER DEFAULT 0 NOT NULL,
  "UPDATE_TIME" TIMESTAMP NULL,
  CONSTRAINT "PK_XXL_JOB_LOG_REPORT" PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."TRIGGER_DAY" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."RUNNING_COUNT" IS '运行中-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."SUC_COUNT" IS '执行成功-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."FAIL_COUNT" IS '执行失败-日志数量';
CREATE UNIQUE INDEX "I_TRIGGER_DAY" ON "XXL_JOB_LOG_REPORT" ("TRIGGER_DAY");

SET IDENTITY_INSERT "XXL_JOB_LOG_REPORT" ON;
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (1, '2024-08-21 00:00:00', 70, 0, 5, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (2, '2024-08-20 00:00:00', 0, 0, 0, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (3, '2024-08-19 00:00:00', 0, 0, 0, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (4, '2024-09-10 00:00:00', 0, 0, 56, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (5, '2024-09-09 00:00:00', 0, 0, 0, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (6, '2024-09-08 00:00:00', 0, 0, 0, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (7, '2024-10-19 00:00:00', 0, 0, 6391, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (8, '2024-10-18 00:00:00', 0, 0, 0, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (9, '2024-10-17 00:00:00', 0, 0, 0, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (10, '2025-02-10 00:00:00', 0, 0, 116, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (11, '2025-02-09 00:00:00', 0, 0, 0, NULL);
INSERT INTO "XXL_JOB_LOG_REPORT" ("ID", "TRIGGER_DAY", "RUNNING_COUNT", "SUC_COUNT", "FAIL_COUNT", "UPDATE_TIME") VALUES (12, '2025-02-08 00:00:00', 0, 0, 0, NULL);
SET IDENTITY_INSERT "XXL_JOB_LOG_REPORT" OFF;

DROP TABLE IF EXISTS "XXL_JOB_LOGGLUE";
CREATE TABLE "XXL_JOB_LOGGLUE" (
  "ID" INTEGER IDENTITY(1,1) NOT NULL,
  "JOB_ID" INTEGER NOT NULL,
  "GLUE_TYPE" VARCHAR2(50) NULL,
  "GLUE_SOURCE" CLOB NULL,
  "GLUE_REMARK" VARCHAR2(128) NOT NULL,
  "ADD_TIME" TIMESTAMP NULL,
  "UPDATE_TIME" TIMESTAMP NULL,
  CONSTRAINT "PK_XXL_JOB_LOGGLUE" PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';

DROP TABLE IF EXISTS "XXL_JOB_REGISTRY";
CREATE TABLE "XXL_JOB_REGISTRY" (
  "ID" INTEGER IDENTITY(1,1) NOT NULL,
  "REGISTRY_GROUP" VARCHAR2(50) NOT NULL,
  "REGISTRY_KEY" VARCHAR2(255) NOT NULL,
  "REGISTRY_VALUE" VARCHAR2(255) NOT NULL,
  "UPDATE_TIME" TIMESTAMP NULL,
  CONSTRAINT "PK_XXL_JOB_REGISTRY" PRIMARY KEY ("ID")
);
CREATE INDEX "I_G_K_V" ON "XXL_JOB_REGISTRY" ("REGISTRY_GROUP", "REGISTRY_KEY", "REGISTRY_VALUE");

DROP TABLE IF EXISTS "XXL_JOB_USER";
CREATE TABLE "XXL_JOB_USER" (
  "ID" INTEGER IDENTITY(1,1) NOT NULL,
  "USERNAME" VARCHAR2(50) NOT NULL,
  "PASSWORD" VARCHAR2(50) NOT NULL,
  "ROLE" TINYINT NOT NULL,
  "PERMISSION" VARCHAR2(255) NULL,
  CONSTRAINT "PK_XXL_JOB_USER" PRIMARY KEY ("ID")
);
COMMENT ON COLUMN "XXL_JOB_USER"."USERNAME" IS '账号';
COMMENT ON COLUMN "XXL_JOB_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "XXL_JOB_USER"."ROLE" IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN "XXL_JOB_USER"."PERMISSION" IS '权限：执行器ID列表，多个逗号分割';
CREATE UNIQUE INDEX "I_USERNAME" ON "XXL_JOB_USER" ("USERNAME");

SET IDENTITY_INSERT "XXL_JOB_USER" ON;
INSERT INTO "XXL_JOB_USER" ("ID", "USERNAME", "PASSWORD", "ROLE", "PERMISSION") VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);
SET IDENTITY_INSERT "XXL_JOB_USER" OFF;

COMMIT;
